version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: wegift
      POSTGRES_USER: wegift
      POSTGRES_DB: wegift
    ports:
      - 5432:5432
