# select build image
FROM clux/muslrust:nightly as build

# create a new empty shell project
RUN USER=root cargo new --bin app
WORKDIR /app

# copy over your manifests
#COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml
COPY ./diesel.toml ./diesel.toml
COPY ./Rocket.toml ./Rocket.toml

# this build step will cache your dependencies
RUN cargo build
RUN rm src/*.rs

# copy your source tree
COPY ./src ./src

# build for release
RUN rm ./target/release/deps/app*
RUN cargo build

# our final base
FROM clux/muslrust:nightly

# copy the build artifact from the build stage
COPY --from=build /app/target/release/app .

# set the startup command to run your binary
CMD ["./app"]