FROM rustlang/rust:nightly as build

WORKDIR /usr/src/myapp

COPY ./Cargo.toml ./Cargo.toml
COPY ./diesel.toml ./diesel.toml
COPY ./Rocket.toml ./Rocket.toml

COPY ./src ./src

RUN cargo build --release

CMD cargo run

# our final base
FROM clux/muslrust:nightly

# copy the build artifact from the build stage
COPY --from=build /my_project/target/release/my_project .

# set the startup command to run your binary
CMD ["./my_project"]