##[development]
##port = 8080
##log = "debug"
##
##[development.databases]
##postgres = { url = "postgres://wegift:wegift@localhost/wegift" }
##
##[production]
##port = 3000
##log = "normal"
##
##[production.databases]
##postgres = { url = "postgres://wegift:wegift@postgres/wegift" }