name: Matrix

on:
  workflow_dispatch:

jobs:
  run-martrix:
    strategy:
      matrix:
        os: [self-hosted, linux, X64]
        version: [1,2,3,4,5,6,7,8,9]
    runs-on: ${matrix.os}
    steps:
        - name: simple
          run: |
            echo "Hello from: "${{ matrix.version}}"
